
title: A propos TienDuy
url: ''
baseurl: '/cv/' #change it according to your repository name



# Profile information
yourname: TienDuy Nguyen  ## put your name
title: 'Ingénieur BIM'  ## your title
location: Paris, France


## Social Profiles
facebook: https://www.facebook.com  ## your facebook account url
twitter: https://twitter.com/TienDuyNGUYEN1  ## your twitter account url
linkedin: https://www.linkedin.com/in/tienduy-nguyen/  ## your linkedin account url
github: https://github.com/tienduy-nguyen  ## you dribbble account url




# Update all the sections by editing the files inside _includes folder.
